version: '3.9'
services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - 5432:5432
#    volumes:
#      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${APP_DB_NAME}
      - POSTGRES_PASSWORD=${APP_DB_OWNER_PASS}
      - POSTGRES_USER=${APP_DB_OWNER_USER}
    healthcheck:
      test: ["CMD", "psql", "-U", "${APP_DB_OWNER_USER}", "-d", "${APP_DB_NAME}", "-c", "select now()"]
      interval: 1s
      timeout: 3s
      retries: 10
  migrations:
    image: migrate/migrate:v4.17.0
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
        - ./db/migrations:/migrations
    command: "-path=/migrations/ -database postgres://${APP_DB_OWNER_USER}:${APP_DB_OWNER_PASS}@postgres/${APP_DB_NAME}?sslmode=disable up"
  migrations-testdata:
    image: migrate/migrate:v4.17.0
    depends_on:
      migrations:
        condition: service_completed_successfully
    volumes:
        - ./db/migrations:/migrations
    command: '-path=/migrations/testdata -database postgres://${APP_DB_OWNER_USER}:${APP_DB_OWNER_PASS}@postgres/${APP_DB_NAME}?sslmode=disable\&x-migrations-table=testdata_migrations up'
  redis:
    image: redis:7.2.3-alpine
    environment:
      - INITIAL_PORT=6379
      - REDIS_CLUSTER=0.0.0.0
      - IP=0.0.0.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379-6384:6379-6384"
