log:
  level: DEBUG # one of DEBUG, INFO, WARN, ERROR
http:
  address: 127.0.0.1:18080
  shutdownTimeout: 3s # timeout for graceful shutdown
  shutdownDelay: 5s # delay before starting shutdown, to allow for load balancer to stop sending traffic
  readTimeout: 15s
  writeTimeout: 15s
db:
  url: postgres://app@127.0.0.1:5432/app_db
  password: app_pwd
  maxConnections: 4
redis:
  clusterMode: true
  opts:
    addrs:
      - localhost:6379
